export const metadata = {
    title: "Ballroom Altovalle :: Referentes",
    description: "destacadosGenerated by create next app",
};

export default function Referentes(){
    return (
    <main className="holder">
            <div className="historia">
                <h2>Historia</h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem velit natus laudantium qui dolore
                    impedit quam obcaecati iste saepe! Nulla, quaerat facere. Pariatur, perspiciatis corrupti.
                    Doloremque accusamus nemo eligendi debitis?</p>

            </div>
            <div className="staff">
                <h2>Referentes</h2>
                <div className="personas">
                    <div className="referente">
                        <img src="/img/ballroom-1.jpeg" />
                        <h5>1111</h5>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur voluptatem dicta
                            dignissimos nemo nam deserunt rem officiis iusto? Fugit, nam mollitia? Beatae, rem sint
                            dolores ut quasi aliquam maxime temporibus?</p>

                    </div>
                    <div className="referente">
                        <img src="/img/ballroom-2.jpeg" />
                        <h5>1111</h5>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur voluptatem dicta
                            dignissimos nemo nam deserunt rem officiis iusto? Fugit, nam mollitia? Beatae, rem sint
                            dolores ut quasi aliquam maxime temporibus?</p>

                    </div>
                    <div className="referente">
                        <img src="/img/ballroom-3.jpeg" />
                        <h5>1111</h5>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur voluptatem dicta
                            dignissimos nemo nam deserunt rem officiis iusto? Fugit, nam mollitia? Beatae, rem sint
                            dolores ut quasi aliquam maxime temporibus?</p>

                    </div>
                    <div className="referente">
                        <img src="/img/ballroom-4.jpeg" />
                        <h5>1111</h5>
                        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Consectetur voluptatem dicta
                            dignissimos nemo nam deserunt rem officiis iusto? Fugit, nam mollitia? Beatae, rem sint
                            dolores ut quasi aliquam maxime temporibus?</p>

                    </div>
                </div>
            </div>
        </main>
        
    )
}