import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import Nav from "@/components/Nav";

export const metadata = {
  title: "Ballroom Altovalle",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body inject_newsvd="true">
        <header>
          <div className="holder">
            <div className="logo">
            <img src="/img/ballroom altovalle logo.png" width="100" alt="..."/> 
              <h1>Ballroom Altovalle</h1>
            </div>
          </div>
        </header>
        <Nav />
        {children}

        <footer>
          <p>Goblinkon 007</p>
        </footer>
      </body>
    </html>
  );
}
