import NovedadItem from "@/components/NovedadItem";

export const metadata = {
    title: "Ballroom Altovalle :: Fechas",
    description: "destacadosGenerated by create next app",
};

export default async function Novedades(){

    const data= await fetch (`${process.env.NEXT_APP_API_URL}/api/novedades`)
    const novedades = await data.json();
    return (
        <section className="holder">
            <h2>Fechas</h2>
            {
                novedades.map(item => <NovedadItem key={item.id}
                    title={item.titulo} subtitle={item.subtitulo}
                    body={item.cuerpo} />
                )
            }
            
           {/* <NovedadItem/> */}
        </section>
    )
}