import ContactForm from "@/components/ContactForm";
import '@/styles/registros.css'
export const metadata = {
    title: "Ballroom Altovalle :: Registros",
    description: "destacadosGenerated by create next app",
};

export default function Contacto(){
    return (
        <main className="holder contacto">
            <div className="columna">
                <h2>Complete el siguiente formulario</h2>
              <ContactForm postUrl={`${process.env.NEXT_APP_API_URL}/api/contacto`} />
            </div>
            <div className="columna datos">
                <h2>Otras vias de contacto</h2>
                <p>Tambien puede contactarse con nosotros usando los siguientes modos</p>
                <ul>
                    <li>Instagram:</li>
                    <li>Instagram:</li>
                    <li>Instagram:</li>
                    <li>Instagram:</li>
                </ul>
            </div>
        </main>
    )
}